
[[introduction, Chapter 1, Introduction]]

==  Introduction 


=== Purpose

The CfRadial2 format is intended to provide a standard, modern, self-describing way to store radar and lidar data in native radial (polar) coordinates.

CfRadial2 is built on NetCDF-4, which is in turn built on HDF5. NetCDF-4 and HDF5 are both up-to-date technology for efficiently and easily storing scientific and engineering data.

The purpose of this document is to specify a CF2-compliant NetCDF format for radar and lidar moments data in radial (i.e. polar) coordinates.

The intention is that the format should, as far as possible, comply with the CF conventions for gridded data. However, the current CF 2.0 convention does not support radial radar/lidar data. Therefore, extensions to the conventions will be required.

The current CF conventions are documented at:

link:$$http://cfconventions.org/$$[http://cfconventions.org/]

link:$$http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.pdf[Version 1.8 pdf]


=== On-line location

This document, and other related information, is on-line at:

link:$$https://github.com/NCAR/CfRadial/docs$$[CfRadial Repository]


[[terminology, Section 1.3, "Terminology"]]
=== Terminology CfRadial1 and CfRadial2

We will refer to CfRadial 2.1, and future 2.x versions, collectively as CfRadial2.

The previous versions, 1.1 though 1.4, will be referred to collectively as CfRadial1.


=== History

CfRadial was introduced in 2011 as a format designed to store data from scanning weather radars and lidars in an accurate and lossless manner.

Since digital weather radars made their debut in the 1970s, a wide variety of data formats has emerged for pulsed instruments (radar and lidar) in polar coordinates. Researchers and manufacturers have tended to develop formats unique to their instruments, and since 1990 NCAR has supported over 20 different data formats for radar and lidar data. Researchers, students and operational users spend unnecessary time handling the complexity of these formats.

CfRadial grew out of the need to simplify the use of data from weather radars and lidars and thereby to improve efficiency. CfRadial adopts the well-known NetCDF framework, along with the Climate and Forecasting (CF) conventions. It is designed to accurately store the metadata and data produced by the instruments, in their native polar coordinates, without any loss of information. Mobile platforms are supported. Data field identification is facilitated by the 'standard_name' convention in CF, so that fields derived from algorithms (such as hydrometeor type) can be represented just as easily as the original fields (such as radar reflectivity).


// [[table-attributes]]
// .Attributes
// [options="header",cols="6,2,2,8,12",caption="Table 1.1. "]
// |===============
// |{set:cellbgcolor!}
// Attribute
// | Type
// | Use
// | Links
// | Description

// [[table-attributes]]
// .Attributes
//Table 1.1: History of CfRadial versions

[[table-history]]
.History of CfRadial versions
[cols=",,",options="header",caption="Table 1.1. "]
|===
| *Date* | *Version* | *Remarks*
| 2011/02/01 | 1.1 | First operational version. NetCDF classic data model.
| 2011/06/07 | 1.2 | Minor changes / additions. NetCDF classic data model.
| 2013/07/01 | 1.3 | Major changes / additions. NetCDF classic data model.
| 2016/08/01 | 1.4 | Major additions – data quality, spectra. NetCDF classic data model.
| 2017/06/02 | 2.0 DRAFT | Major revision - not backward compatible with CfRadial1 +
Uses NetCDF 4 and groups. +
Combines CfRadial 1.4 and ODIM_H5 version 2.2. +

| 2019/02/03 | 2.0 DRAFT a|
{empty}(a) ray_angle_res changed to ray_angle_resolution +
(b) fixed_angle changed to sweep_fixed_angle +
(c) Added sweep modes: doppler_beam_swinging, complex_trajectory and electronic_steering. +
2.0 deprecated on 2019/09/01. +
| 2019/09/01 | 2.1 DRAFT | A number of issues were raised related to draft version 2.0. +
The 2.1 draft addresses those and is not backward compatible with version 2.0. +
|===

CfRadial1 has been adopted by NCAR, as well as NCAS (the UK National Center for Atmospheric Science) and the US DOE Atmospheric Radiation Measurement (ARM) program. CfRadial development was boosted in 2015 through a two-year NSF EarthCube grant to improve CF in general. Following the CF user community workshop in Boulder Colorado in May 2016, version 1.4 was agreed upon, adding explicit support for quality fields and spectra.

CfRadial2 has been proposed as an official exchange format for the WMO.

=== CF2 and CfRadial2

In 2015 the US National Science Foundation (NSF) funded the project “EarthCube IA: Advancing NetCDF-CF for the Geoscience Community". This project aims to update the CF conventions to make better use of NetCDF4 capabilities, such as groups, to organize data in CF-compliant files. CF2.0 standards will be developed to guide this process. The development of CfRadial2 is part of this work. A workshop was held in Boulder Colorado, in May 2016, to assess and collaborate on progress to Cf2.0.

Shortly after that, in July 2016, a WMO-sponsored meeting was held at NCAR in Boulder, during which the WMO Task Team on Weather Radar Data Exchange (TT-WRDE) considered the adoption of a single WMO-recommended format for radar and lidar data in polar coordinates. The two modern formats discussed as options were CfRadial and the European operational radar community ODIM_H5 (HDF5) format (Michelson et al. 2014), in addition to the older and more rigid table-driven BUFR and GRIB2 formats. TT-WRDE recommended that CfRadial 1.4 be merged with the sweep-oriented structure of ODIM_H5, making use of groups to produce a single WMO format that will encompass the best ideas of both formats. That has led to the emergence of CfRadial2. This format should meet the objectives of both the NSF EarthCube CF 2.0 initiative and the WMO.

=== On-line URLs

This document, older versions, full history and other related information, are available on-line at:

link:$$https://github.com/NCAR/CfRadial/tree/master/docs$$[github docs]

These include detailed documentation of versions 1.1 through 1.4, as well as the current CfRadial2 development.

The current NetCDF CF conventions are documented at:

link:$$http://cfconventions.org/$$[http://cfconventions.org/]

link:$$http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.pdf[Version 1.8 pdf]


